### ISSUE TITLE
ESM compatibility for native plugins 

### ISSUE THREAD

**Issue by ClementValot** [danielgindi/rollup-plugin-natives#14]
When bundling with rollup and exporting ESM code (`rollupConfig.output.format == 'es'`), the rollup-plugin-natives outputs .node dependencies as require: `var cpufeatures = require("./cpufeatures.node");` which causes `ReferenceError: require is not defined in ES module scope, you can use import instead` at runtime. 

Additionally, node ESM doesn't support ".node" imports natively (see https://github.com/nodejs/node/issues/40541 ) 

Workaround I used is appending `import { createRequire } from 'module';
const require = createRequire(import.meta.url);` at the top of the bundle file. 

Something similar could be implemented in the meantime until ESM actually supports native imports

**Comment by danielgindi** [comment]
This would have to be a flag in the module options, to specify that you are exporting as ESM.
Do you want to make a PR?

**Comment by danielgindi** [comment]
Supported in 0.7.6
