### ISSUE TITLE
Can't get it working for sharp

### ISSUE THREAD

**Issue by pedroterzero** [danielgindi/rollup-plugin-natives#18]
I'm fairly sure I'm just missing something here, but I can't seem to get this to work for sharp.

Here is a minimal testcase: https://github.com/pedroterzero/rollup-native-sharp-testcase

Any pointers where I am going wrong would be great.

Additional info: If I run `npm run bundle` in the testcase, then `node dist/index.js` has the following output (and `dist/libs` is empty):

```
/app/dist/index.js:1400
	  throw new Error(help.join('\n'));
	  ^

Error: 
Something went wrong installing the "sharp" module

Could not dynamically require "../build/Release/sharp-linuxmusl-x64.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
```

**Comment by danielgindi** [comment]
I believe you need to set `targetEsm: false` and also set `destDir`

**Comment by Merlin04** [comment]
I'm also having this issue when trying to get this plugin to work with targetEsm set to true. It seems the `createRequire` code isn't being added to the bundle at all. As a workaround, I've set my rollup config's `output.banner` to the following:

```
        banner: `#!/usr/bin/env node
import { fileURLToPath } from "url";
import { dirname } from "path";
import { createRequire } from "module";
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const require = createRequire(import.meta.url);

`
```

and I've set the `ignoreDynamicRequires` property of the commonjs plugin config to true. (also had to disable `compress` in terser config for some reason)

**Comment by danielgindi** [comment]
Yes you may need `ignoreDynamicRequires`
