### ISSUE TITLE
Maybe I found a BUG 🤔

### ISSUE THREAD

**Issue by caoxiemeihao** [danielgindi/rollup-plugin-natives#19]
https://github.com/danielgindi/rollup-plugin-natives/blob/455f101971d12a61ca3bdbb2422ce25a8a14929f/src/index.js#L197

https://github.com/danielgindi/rollup-plugin-natives/blob/455f101971d12a61ca3bdbb2422ce25a8a14929f/src/index.js#L239

They are actually the same? Is this the expected behavior?

**Comment by danielgindi** [comment]
These are not the same regexes

**Comment by caoxiemeihao** [comment]
`hasBindingReplacements` is assigned twice, and the second assignment will overwrite the first assignment.
