### ISSUE TITLE
doesn't recognize sharp

### ISSUE THREAD

**Issue by mmomtchev** [danielgindi/rollup-plugin-natives#8]
When trying to rollup a bundle with the `sharp` package I get this error:

```
mmom@mmom-workstation:~/src/top-secrect-project$ rollup -c

server.js → ./build/top-secret-server.min.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
critters (imported by critters?commonjs-external)
[!] Error: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
node_modules/sharp/build/Release/sharp.node (1:0)
1: ELF>��@x=@8@"�" �(�($�($�� 8,8,$8,$@���$$P�td � � ���Q�tdR�td�(�($�($ppGNU{���N;���RШ�$[b���� 
                                                                                                 B�0�����$�)�HA #\c@�@�2�F ���)�
   ^
F�aP��D(A� 	� $0L@���b  b��  @D*b@�)�		 !�@��H�@H�  c �
3  
  ڐFa�%@
        Q�A fl  @R݀$0����H@ � D�0�35678:<?@ABDEFHIJKLMOPSUWZ[^`acdghjklmoqrsvyz{|~���������������������������������������������������������������p
```

This is the `require` that should have triggered the plugin:

```js
  require('../build/Release/sharp.node');
```

**Comment by danielgindi** [comment]
With what version are you seeing this?

**Comment by danielgindi** [comment]
@mmomtchev if you moved to using the latest version and it works for you please close the issue

**Comment by mmomtchev** [comment]
It is the latest version - 0.7.1 - and I just found that the issue goes away if `rollup-plugin-natives` is specified before `plugin-node-resolve` and `plugin-commonjs` in the plugin chain. Is this an expected behavior?

**Comment by danielgindi** [comment]
> It is the latest version - 0.7.1 - and I just found that the issue goes away if `rollup-plugin-natives` is specified before `plugin-node-resolve` and `plugin-commonjs` in the plugin chain. Is this an expected behavior?

Well yes it is :) because if node-resolve and commonjs come first, they try to read the referenced `.node` files, which are native library binaries. And obviously they should fail on it...
